site_name: GenQR Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: usage.md
  - API Reference: api_reference.md

plugins:
  - search
  - mkdocstrings

