site_name: GenQR Documentation

theme:
  name: material

nav:
  - Home: docs/index.md
  - Getting Started: docs/usage.md
  - API Reference: docs/api_reference.md

plugins:
  - search
  - mkdocstring
